name: no_cg_no_life_app
description: No CG No Life - EWU, is a community driven app for EWU students.

publish_to: 'none'

# A version number is three numbers separated by dots, like 1.2.43+1
# followed by an optional build number separated by a +.
version: 1.0.0+1 # <major_version>.<minor_version>.<bug_fixed>+<build_number>

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  page_transition: "^2.0.2"
  url_launcher: ^6.0.8
  syncfusion_flutter_gauges: ^19.2.44
  scoped_model: ^2.0.0-nullsafety.0 # TODO: update this version to a stable version if a stable version is released.
  flutter_datetime_picker: ^1.5.1


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
